name: Backend CI - Spring Boot

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Optimiza el tiempo descargando librerías solo si cambian

      - name: Construir con Maven
        run: mvn -f backend/pom.xml clean package -DskipTests
        # Nota: Quité "-branch main" porque no es un comando válido de Maven. 
        # El contexto de la rama lo maneja el Checkout.

      - name: Subir Artefacto (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend/target/*.jar
          retention-days: 5
